---
- name: Hapus banyak user
  hosts: all
  become: yes
  tasks:
    - name: Hapus user-user tertentu
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - user1
        - user2
        - user3
